### ISSUE TITLE
slidy create example vs 2.1.1 Unhandled exception

### ISSUE THREAD

**Issue by andrewbiller** [Flutterando/slidy#177]
Running command: slidy create example

```
Unhandled exception:
FileSystemException: Cannot open file, path = 'pubspec.yaml' (OS Error: O sistema não pode encontrar o arquivo especificado.
, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:549:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:594:18)
#4      _File.readAsLinesSync (dart:io/file_impl.dart:600:36)
#5      generateScript (package:slidy/src/modules/start.dart:102:19)
#6      selecStateManagement.<anonymous closure> (package:slidy/src/modules/start.dart:153:13)
<asynchronous suspension>
#7      selecStateManagement.<anonymous closure> (package:slidy/src/modules/start.dart)
#8      start (package:slidy/src/modules/start.dart:195:20)
<asynchronous suspension>
#9      startSlidyCreate (package:slidy/src/modules/create.dart:59:3)
#10     startFlutterCreate.<anonymous closure>.<anonymous closure> (package:slidy/src/modules/create.dart:51:9)
```

Slidy 2.0.0+1 working fine
Dart version: Dart VM version: 2.8.4 (stable) (Wed Jun 3 12:26:04 2020 +0200) on "windows_x64"

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):                                           
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [versÃ£o 10.0.18363.900], locale pt-BR)    
                                                                                                      
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)                  
[√] Android Studio (version 4.0)                                                                      
[√] VS Code (version 1.37.0)                                                                          
[√] Connected device (1 available)   
```                                                                 
                                                                                                      
• No issues found!

**Comment by jacobaraujo7** [comment]
Please update your slidy. 
Fix it!
