### ISSUE TITLE
Unknown "g" command crashes slidy

### ISSUE THREAD

**Issue by Ascenio** [Flutterando/slidy#233]
**The problem**
If a incomplete command is ran then slidy crashes. For example, if I execute something as `slidy g b` the following is shown:
```sh
Unhandled exception:
Bad state: No element
#0      ListMixin.single (dart:collection/list.dart:119:22)
#1      GenerateBlocSubCommand.run (file:///home/ascenio/.pub-cache/hosted/pub.dartlang.org/slidy-3.0.0+2/bin/commands/sub_command/generate_bloc_sub_command.dart:43:74)
#2      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
#3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#4      new Future.sync (dart:async/future.dart:218:31)
#5      CommandRunner.run (package:args/command_runner.dart:112:14)
#6      executeCommand (file:///home/ascenio/.pub-cache/hosted/pub.dartlang.org/slidy-3.0.0+2/bin/slidy.dart:37:10)
#7      main (file:///home/ascenio/.pub-cache/hosted/pub.dartlang.org/slidy-3.0.0+2/bin/slidy.dart:17:5)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Notice that I didn't added the arguments as expected (`slidy g b login_bloc`, for example), but this should be handled by the program, as the user is expected to send invalid or absent args.

**Expected behavior**
Slidy should be able to gracefully handle the error and just print the list of available subcommands (same as `slidy g`)

**Comment by jacobaraujo7** [comment]
fixed
