### ISSUE TITLE
Error when using install command

### ISSUE THREAD

**Issue by GabrielDiBastiani** [Flutterando/slidy#247]
Slidy version: 3.0.2

When I run `slidy i <package_name>` it threw an exception.

```shell
PS C:\Users\gbast\Downloads\Projects\App\tripeeapp-flutter> slidy i built_value
Unhandled exception:
NoSuchMethodError: The getter 'value' was called on null.
Receiver: null
Tried calling: value
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      PubspecServiceImpl.add (package:slidy/src/core/services/pubspec_service_impl.dart:128:36)
<asynchronous suspension>
#2      PackageInstalationRepositoryImpl.install (package:slidy/src/modules/package_instalation/infra/repositories/package_instalation_repository.dart:29:22)
<asynchronous suspension>
#3      Install.call (package:slidy/src/modules/package_instalation/domain/usecases/install.dart:15:12)
#4      InstallCommand.run (file:///C:/Users/gbast/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/slidy-3.0.2/bin/commands/install_command.dart:26:24)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
```

```shell
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [versÃ£o 10.0.19042.867], locale pt-BR)
    • Flutter version 2.0.4 at C:\Users\gbast\flutter
    • Framework revision b1395592de (5 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\gbast\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.55.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.63

• No issues found!
```

**Comment by jacobaraujo7** [comment]
FIXED!!
Version 3.1.0
